### ISSUE TITLE
Clarify aliasing

### ISSUE THREAD

**Issue by jimon** [gingerBill/gb#10]
There are tons of functions in gb_math with declaration similar to `gb_mat4_mul(gbMat4 *out, gbMat4 *m1, gbMat4 *m2)`. Would be nice to have a clarification if out can point to either of inputs or not. Because looks like most of functions are safe to use when we reuse one of inputs as output, but I'm not 100% sure :)

**Comment by gingerBill** [comment]
I'm not overly concerned about specifying the aliasing. If I want to specify that they don't alias, I would use `restrict` so I think it's okay to assume that they can without `restrict`.

**Comment by jimon** [comment]
Ah ok, I see you have on stack buffers in place to accommodate aliasing case 👍
