### ISSUE TITLE
Missing check in gb_ucs2_to_utf8 - gb.h

### ISSUE THREAD

**Issue by spanzeri** [gingerBill/gb#12]
In gb_ucs2_to_utf8, in the case of surrogate UTF-6 chars, there is only a check for the first u16.
`else if (*str >= 0xd800 && *str < 0xdc00)` 

I believe it should also check that the second u16 is valid:
`if (Src[1] < 0xDC00 || Src[1] >= 0xE000) return NULL;`

It should work fine with UCS2 as, in theory, surrogate are not part of the encoding.
It might not check properly in case of UTF-16.

**Comment by gingerBill** [comment]
The second check isn't needed for UCS2. I might do a UTF-16 version too in the future.
