### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [gingerBill/gb#3]
I would like to point out that identifiers like "[`__GB_NAMESPACE_START`](https://github.com/gingerBill/gb/blob/21c240a8ae4500a9c121cbabd301da6e5235fc01/gb.hpp#L338)" and "[`gb__string_realloc`](https://github.com/gingerBill/gb/blob/21c240a8ae4500a9c121cbabd301da6e5235fc01/gb_string.h#L494)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by gingerBill** [comment]
I do know this but I have never seen this be a problem in the wild, ever. If you can show me an example when this is a problem please do so. 

However, I will be retiring gb.hpp soon and completely replacing it with gb.h. gb.h will be C compatible and be a better tool all round for my needs. gb.hpp was good but I am find gb.h to better for my uses as I am programming in C and C-styled C++ more and more these days.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?

**Comment by gingerBill** [comment]
Which parts (apart from the naming of those identifiers)?

**Comment by elfring** [comment]
Would you like to [change the usage of (double) underscores in affected identifiers](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797)?

**Comment by gingerBill** [comment]
I won't need to as I will remove this library soon and fully replace it with gb.h. gb.h is still missing many features but they won't be hard to implement.
