### ISSUE TITLE
Quaternion slerp fairly broken

### ISSUE THREAD

**Issue by zao** [gingerBill/gb#38]
`gb_quat_slerp` seems to be fairly broken, it yields rather large results or nans/infs for well-formed input and does not agree at all with `gb_quat_slerp_approx` or `gb_quat_nlerp`.

For example, the following non-tricky interpolation results in a magnitude of over 2, and small angle actual data yielded magnitudes in the thousands in my application:
```cpp
gbMat4 ma, mb;
gb_mat4_rotate(&ma, gb_vec3(1.0f, 0.0f, 0.0f), 0.3f);
gb_mat4_rotate(&mb, gb_vec3(1.0f, 0.0f, 0.0f), 1.2f);

gbQuat q, qa, qb;
gb_quat_from_mat4(&qa, &ma);
gb_quat_from_mat4(&qb, &mb);

gb_quat_slerp(&q, qa, qb, 0.2f);
float mq = gb_quat_mag(q);
```
If one contrasts the implementation with the Wikipedia [example code](https://en.wikipedia.org/wiki/Slerp#Source_code) the `gb_math.h` implementation seems to eventually differ mathematically in two places:
`s1 = gb_sin(1.0f - t*angle);` ought to be `s1 = gb_sin(angle - t*angle);`
`gb_quat_mulf(&x, z, s1);` ought to be `gb_quat_mulf(&x, a, s1);`

Once those two changes are in place, the output agrees with `gb_quat_slerp_approx`.

**Comment by zao** [comment]
Was the removal of the declaration of the function intended in 23c3fba?
Is it not supposed to be part of the public interface?

**Comment by gingerBill** [comment]
Removal? Whoops. That was not meant to happen.

**Comment by zao** [comment]
While poking around in the function, I noticed that it's slightly dangerous for quaternions that are close to each other.

Wikipedia's implementation has a different threshold for the branch where falling back to regular lerp to cover small angles. If not, dividing by sin(angle) approaches dividing by zero.
