### ISSUE TITLE
Mac OS X Inline Assembly

### ISSUE THREAD

**Issue by amittaigames** [gingerBill/gb#7]
I know this is not built with immediate Mac support, but I thought I should draw your attention to an error I've received when building with GB.

```
error: invalid use of a cast in a inline asm context requiring an l-value: remove the cast or build with -fheinous-gnu-extensions
```

The trace says line 3622 of gb.h underlining `cast(u8 *gb_restrict)dest` and `cast(u8 *gb_restrict)source`

**Comment by gingerBill** [comment]
Thank you for the notice. I'll fix this in the next update.
