### ISSUE TITLE
Setting number of color bits in opengl pixel format

### ISSUE THREAD

**Issue by johnburton** [gingerBill/gb#8]
In https://github.com/gingerBill/gb/blob/master/gb.h line 8971
I believe this should be set to 24 and not 32 :-
`pfd.cColorBits = 32;`
As according to https://msdn.microsoft.com/en-us/library/windows/desktop/dd368826(v=vs.85).aspx and other sources, the size does not include the alpha bits, only the RGB part. (And when I try similar and call DescribePixelFormat it's given me a format with it set to 24 anyway.

Probably no big deal even if true, but seemed worth mentioning.

**Comment by gingerBill** [comment]
Yeah that's the weird thing. On my computer (and few others) 32 seems to be correct. If you get the default values, it goes to 32 not 24. 
See this episode of Handmade Hero where Casey has the same "problem": https://youtu.be/5Klc9RZPG7M?t=3143
